src/virtual_machine.cpp, src/virtual_machine.hpp, src/vm_interpreted.cpp, src/vm_interpreted.hpp, src/vm_interpreted_light.cpp, src/vm_interpreted_light.hpp
This fixes some bugs when using non-default Dataset sizes. See also issue #45.
=> Support Dataset size larger than 4 GiB

CMakeLists.txt
This fixes compilation issues when librandomx is built alone and not under Monero's cmake.
=> Fix cmake standalone build

src/vm_interpreted.cpp, src/vm_interpreted.hpp, src/vm_interpreted_light.hpp
* to formally match the specification
* a small increase in interpreted mining speed (~4%)
=> Add Dataset prefetch in interpreted VM

CMakeLists.txt, makefile, src/intrin_portable.h
Added altivec functions to support future jit compiler. Sadly IBM's AES implementation is not compatible with intels, see https://stackoverflow.com/questions/56027569/is-there-a-fast-way-to-make-ibms-vncipher-instruction-result-the-same-as-intels
=> Added POWER7+ intrinsincs and cpu detection to makefile

doc/design.md, doc/specs.md, src/aes_hash.cpp, src/tests/benchmark.cpp, src/tests/rng-tests.cpp
* this fixes identical sequences of columns 0/2 and 1/3 if their states are the same
* added [TestU01](https://en.wikipedia.org/wiki/TestU01) results for AesGenerator1R and AesGenerator4R
* added a note about the reversibility of AesHash1R
=> Different round keys for columns 0,1 and 2,3 in AesGenerator4R

makefile, src/affinity.cpp, src/affinity.hpp, src/common.hpp, src/tests/benchmark.cpp, src/tests/utility.hpp
Adds a thread affinity mask option for allowing to set miner threads to specific cpus/cores. Accepts a hex or decimal value representing a bitmask.
E.g. `--threads 4 --affinity 0x1D`, equates to our 4 threads `t1,t2,t3,t4` and a mask `11101`, which yields: ` (t4, cpu4), (t3, cpu3), (t2, cpu2), (t1, cpu0)`. So cpu is the bit position (right-to-left) and each `1` sequentially is the next thread.
Useful for benchmarking multi-processor/NUMA node systems.
=> benchmark: add thread affinity mask option

src/common.hpp
Overflow is possible here if Dataset size is over 4 GiB.
https://github.com/tevador/RandomX/blob/2706a8b7533860900b33ac69899471e5127a4872/src/randomx.cpp#L123
Also added a `static_assert` to limit Dataset to a maximum of 16 GiB.
=> Fix: possible overflow when using non-standard Dataset size

src/aes_hash.cpp, src/assembly_generator_x86.cpp, src/blake2_generator.cpp, src/blake2_generator.hpp, src/bytecode_machine.cpp, src/common.hpp, src/jit_compiler_x86.cpp, src/superscalar.cpp, src/tests/perf-simulation.cpp
* Blake2Generator::getInt32 renamed to getUInt32 to avoid confusion
* isPowerOf2 renamed to isZeroOrPowerOf2 to avoid confusion
* added asserts to validate the input/output size of AES functions
* fixed possible overflow in JitCompilerX86::getCodeSize (unused function)
=> Refactoring

doc/configuration.md, src/common.hpp, src/randomx.cpp
=> Do not attempt to allocate >= 4 GiB on 32-bit systems

doc/configuration.md, src/common.hpp, src/jit_compiler_x86.cpp, src/jit_compiler_x86.hpp, src/jit_compiler_x86_static.S, src/jit_compiler_x86_static.asm, src/tests/jit-performance.cpp, src/virtual_memory.cpp, src/virtual_memory.hpp
* code buffer size is calculated based on RandomX parameters
* added a maximum value constraint for program size and superscalar latency
* reduced the x86 code size of memory instructions by 1 byte
* disclaimer note in configuration documentation
=> Fix: hardcoded JIT code buffer size

src/jit_compiler_x86_static.S
Fixes a compiler error which looks like this:
```
/Users/user/wrk/play/xmrig/src/crypto/randomx/jit_compiler_x86_static.S:71:40: error: unexpected token in argument list
movapd xmm13, xmmword ptr mantissaMask[rip]
^
/Users/user/wrk/play/xmrig/src/crypto/randomx/jit_compiler_x86_static.S:72:34: error: unexpected token in argument list
movapd xmm14, xmmword ptr exp240[rip]
```
=> Fix a compiler error on Apple OSX because the assembly is not understood

src/dataset.cpp, src/jit_compiler_x86.cpp, src/jit_compiler_x86.hpp, src/randomx.cpp, src/randomx.h, src/tests/benchmark.cpp, src/virtual_memory.cpp, src/virtual_memory.hpp, src/vm_compiled.cpp, src/vm_compiled.hpp, src/vm_compiled_light.cpp, src/vm_compiled_light.hpp
Optional because it has significant impact on mining performance (-30%). Almost no impact on verification performance.
=> Optional W^X policy for JIT pages

src/asm/program_loop_load.inc, src/asm/program_loop_store.inc, src/jit_compiler_x86.cpp, src/jit_compiler_x86.hpp, src/jit_compiler_x86_static.S, src/jit_compiler_x86_static.asm, src/jit_compiler_x86_static.hpp
Prefetches scratchpad data as soon as it's possible to calculate data address for the next load.
~1.2% speedup on my Ryzen 7 3700X (from 8707 h/s up to 8814 h/s).
=> Optimized loading from scratchpad

src/jit_compiler_a64_static.S
ldr/madd instruction sequence makes compiled binary crash, so separate them.
=> Workaround for a bug in binutils-2.32-1 on ARM

src/instructions_portable.cpp, src/intrin_portable.h
Compiling with gcc on win32 is broken. This breaks gitian/depends builds of Monero.
=> Fix for win32 build with gcc

CMakeLists.txt
Needed for Monero GUI builds, we need the output library to link against it.
=> CMake install target for randomx library

src/dataset.hpp, src/randomx.cpp, src/randomx.h, src/virtual_machine.hpp
Make init_cache and set_cache no-ops if fed the same data as before
This is just a suggestion; it could make some code in monerod a tiny bit simpler if we
didn't have to track cache contents so closely. (E.g. https://github.com/monero-project/monero/pull/5948) Feel free to close if not wanted.
=> Remember cache input data

CMakeLists.txt, src/cpu.cpp, src/cpu.hpp, src/dataset.hpp, src/intrin_portable.h, src/randomx.cpp, src/randomx.h, src/tests/api-example1.c, src/tests/api-example2.cpp, src/tests/benchmark.cpp, vcxproj/randomx.vcxproj, vcxproj/randomx.vcxproj.filters
Can autodetect AES, SSSE3 and AVX2 and sets the JIT flag if supported.
Usage:
```c
randomx_flags flags = randomx_get_flags();
randomx_cache *myCache = randomx_alloc_cache(flags);
randomx_init_cache(myCache, &myKey, sizeof myKey);
randomx_vm *myMachine = randomx_create_vm(flags, myCache, NULL);
``` 
AES detection on ARM64 needs testing.
=> Automatic detection of CPU capabilities

src/virtual_memory.cpp
OpenBSD's mmap does not support `MAP_HUGETLB` and `MAP_POPULATE`.
=> Fixed mmap on OpenBSD

src/randomx.cpp, src/randomx.h, src/tests/affinity.cpp, src/tests/benchmark.cpp, src/tests/tests.cpp
Since OpenBSD 6.0 W^X is enforced.
Added `RANDOMX_FLAG_SECURE` in tests and benchmarks.
Excluded `cpu_set_t` since it is not defined on OpenBSD.
=> Fixed tests on OpenBSD

src/aes_hash.cpp, src/aes_hash.hpp, src/intrin_portable.h, src/randomx.cpp, src/randomx.h, src/tests/benchmark.cpp, src/virtual_machine.cpp, src/virtual_machine.hpp
Adds more parallelizm into AES loop so modern CPUs can take advantage of it. Also, scratchpad data moves between L1 and L3 caches only one time which saves time and energy per hash.
=> Combined hash and fill AES loop

src/instructions_portable.cpp, src/intrin_portable.h, src/randomx.cpp, src/randomx.h, src/tests/tests.cpp
Technically, the floating point registers are nonvolatile in most calling conventions, so we should preserve their values.
Not preserved for `randomx_calculate_hash_{first,next,last}`, but I added a warning in their description. These functions typically run in worker threads, so altering the rounding mode should not be a big problem there.
=> Preserve floating point state when calling randomx_calculate_hash

src/randomx.cpp, src/virtual_machine.hpp
Happens when the cache is reallocated and intialized with the same key. The VM would keep the old pointer.
This fixes random crashes in test 91.
=> Fix potential use-after-free when reallocating cache

src/jit_compiler.hpp, src/randomx.cpp, src/tests/affinity.cpp, src/tests/benchmark.cpp, src/tests/tests.cpp, src/virtual_memory.cpp
Fixes #186
1. Disables hugepages (not supported).
1. Force W^X (required).
1. When allocating JIT memory, PROT_EXEC must be reserved in order to set the pages executable later.
=> Fix compilation and JIT support on NetBSD

src/jit_compiler_x86.cpp
I believe his hardcoded "8" should actually be RegistersCount, just in case anyone tries to create a variant with more/fewer registers.
=> replace hardcoded literal with its appropriate symbol

src/virtual_memory.cpp
This change makes it possible to enable hardened runtime with `com.apple.security.cs.allow-jit` key instead of `com.apple.security.cs.allow-unsigned-executable-memory`.
A bit ugly with nested `#ifdef`. Apparently there is a crashing issue on macOS 10.13 or lower but I was not able to reproduce it on macOS 10.12: https://github.com/herumi/xbyak/pull/84#issuecomment-562442380
Also does this make issues on iOS or does it use interpreter mode anyway?
=> virtual_memory: add MAP_JIT on macOS

src/jit_compiler_x86.cpp, src/jit_compiler_x86_static.S, src/jit_compiler_x86_static.asm, src/jit_compiler_x86_static.hpp
Because all registers are initialized to 0 at this point, there's no need to XOR them at initialization time.
=> remove unnecessary first-load initialization code

src/jit_compiler_a64.cpp
See https://github.com/xmrig/xmrig/issues/1916
=> Fix illegal instruction crash on some ARM systems

src/virtual_memory.cpp
This is a fixed version of #199. Should also use #198 with this.
With only #198 I get 2279H/s with 8 threads. With this PR added, I get 2328H/s. No improvement with only 1 thread.
=> Faster W^X policy for apple silicon macs

src/asm/program_prologue_linux.inc, src/asm/program_prologue_win64.inc, src/asm/program_read_dataset.inc, src/asm/program_read_dataset_sshash_init.inc, src/jit_compiler_a64_static.S
There was a false dependency on readReg2 and readReg3 (caused by `xor rbp, rax` instruction) when reading dataset item (see design.md - 4.6.2 Loop execution, steps 5 and 7). This change uses `ma` register to read dataset item before the whole `rbp` (`ma` and `mx`) is changed, so superscalar and out-of-order CPU can start executing it earlier.
Results: https://i.imgur.com/Bpeq9mx.png
~1% speedup on modern Intel/AMD CPUs.
=> Optimized dataset read

CMakeLists.txt
=> Fix typo for M1 Mac build

src/cpu.cpp
MinGW GCC 5.3 defines `_WIN32` when cross-compiling to Windows from Linux, 
BTW, `__cpuidex` intrinsic has been added to GCC a few weeks ago (most probably will be in GCC 11 release). Thus the ifdef would need a tweak in foreseeable future.
=> __cpuidex: explicit MSVC check, fix MinGW GCC 5.3 cross-compilation

src/jit_compiler_a64_static.S, src/jit_compiler_x86_static.S, src/jit_compiler_x86_static.asm
Use local symbols instead of global symbols, to prevent problems
with dynamic linker.
Was causing reproducible crashes in monero core_tests.
The .S patches have been tested on ARM and x86-64 Linux. The corresponding .asm patches are untested and need review, perhaps they're not needed.
The crashes were only in debug builds; they use dynamically linked libraries. This bug only hits when librandomx is a shared library.
=> Fix absolute address references

CMakeLists.txt, src/jit_compiler_x86.cpp
MSVC debug/relwithdebinfo builds use jmp trampolines for ASM functions, so these must be traversed to get the actual address of the code for each function.
=> Fixed a crash in MSVC Debug and RelWithDebInfo builds

src/virtual_memory.cpp
`pthread_jit_write_protect_np` undefined on at least Mojave (10.14.6, x86_64).
=> Fix W^X policy for apple portability

src/tests/benchmark.cpp
We forgot to bump the version number for the last two tags.
=> RandomX benchmark 1.1.11

src/intrin_portable.h
Identifiers starting with an underscore followed by an uppercase
letter are reserved for the compiler.
Should fix #228
=> Do not use reserved identifiers in intrin_portable.h

CMakeLists.txt, src/allocator.cpp, src/dataset.cpp, src/jit_compiler_a64.cpp, src/jit_compiler_x86.cpp, src/randomx.cpp, src/virtual_memory.c, src/virtual_memory.h
Too annoying in log messages for non-exceptional conditions.
=> Don't use exceptions in low-level mem allocator

src/randomx.cpp
1. `cache->jit = new randomx::JitCompiler();` - succeeds
2. `cache->memory = (uint8_t*)randomx::LargePageAllocator::allocMemory(randomx::CacheSize);` - fails
3. `if (cache && cache->memory == nullptr) randomx_release_cache(cache);` is executed
4. randomx_release_cache checks `if (cache->memory != nullptr)` and does nothing
5. cache->jit stays allocated
=> Fixed cache->jit memory leak

src/virtual_memory.c
```
virtual_memory.c:210:14: warning: type defaults to 'int' in declaration of 'pageMinimum' [-Wimplicit-int]
```
=> Fixed compiler warning

src/virtual_memory.c
Call sys_icache_invalidate() after pthread_jit_write_protect_np() according to https://developer.apple.com/documentation/apple-silicon/porting-just-in-time-compilers-to-apple-silicon
=> Invalidate CPU I-cache on Apple Silicon

.github/workflows/c-cpp.yml, CMakeLists.txt, src/randomx.cpp
- Compile RandomX on a wide variety of OS and architectures
- Fixed broken x86 (32-bit) builds (it tried to use JIT compiler for them)
- Don't use broken `fesetenv` in msys2 builds: https://sourceforge.net/p/mingw-w64/bugs/541/
=> Added CI tests

src/intrin_portable.h
=> Preserve const qualifier when casting

CMakeLists.txt, src/common.hpp, src/jit_compiler_rv64.cpp, src/jit_compiler_rv64.hpp, src/jit_compiler_rv64_static.S, src/jit_compiler_rv64_static.hpp, src/tests/riscv64_zba.s, src/tests/riscv64_zbb.s
Currently it assumes RV64GC as the baseline, which matches what Linux expects in terms of ISA extensions.
Additionally, when configured with `-DARCH=native`, it will check for the presence of two additional extensions:
* Zba - address generation (useful for the IADD_RS instruction)
* Zbb - basic bit manipulation (useful mainly for rotations)
These two extensions give about a 3-5% speed-up compared to the base ISA and a 10% speed-up for cache initialization (Argon2 is heavy on rotations).
Two additional extensions will be useful in the future: V (for SIMD) and Zkn (for AES), but AFAIK there are currently no chips that support them.
Here are some benchmarks with my StarFive JH7110 based board:
```
> ./randomx-benchmark --auto --mine --largePages --threads 4
RandomX benchmark v1.1.12
- …
```
=> JIT compiler for RISC-V

src/jit_compiler_a64.cpp, src/jit_compiler_a64_static.S
From https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms
> The platforms reserve register x18. Don’t use this register.
This PR fixes invalid hashes when running on Apple silicon with the latest macOS SDK.
=> ARM64 JIT: don't use `x18` register

src/jit_compiler_a64.cpp, src/jit_compiler_a64.hpp
=> Fixed UB in ARM64 JIT compiler

src/assembly_generator_x86.cpp, src/bytecode_machine.cpp, src/jit_compiler_a64.cpp, src/jit_compiler_rv64.cpp, src/jit_compiler_x86.cpp, src/reciprocal.c, src/reciprocal.h, src/tests/perf-simulation.cpp
Also limited it to 32 bit because it's supposed to work only with 32-bit values, according to the specs.
=> Optimized randomx_reciprocal

src/virtual_memory.c
Alpine Linux riscv64 P2Pool builds have this issue.
```
Thread 3 "libuv-worker" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 744]
__munmap (start=0x0, len=2097152) at ./arch/riscv64/syscall_arch.h:28
warning: 28     ./arch/riscv64/syscall_arch.h: No such file or directory
(gdb) bt
#0  __munmap (start=0x0, len=2097152) at ./arch/riscv64/syscall_arch.h:28
#1  0x000000000011a8b2 in randomx::VmBase<randomx::LargePageAllocator, true>::~VmBase (this=0x7ffff28f9000, __in_chrg=<optimized out>)
at /home/runner/work/p2pool/p2pool/external/src/RandomX/src/virtual_machine.cpp:102
#2  0x0000000000118d60 in randomx::CompiledVm<randomx::LargePageAllocator, true, false>::~CompiledVm (this=0x7ffff28f9000, __in_chrg=<optimized out>)
at …
```
=> Fixed a crash on some systems when freeing memory

src/randomx.cpp, src/randomx.h
The similar function already exists for getting dataset's memory.
Created instead of #312 so it can get reviewed
=> Added `randomx_get_cache_memory` API
